# Generated by Django 6.0.1 on 2026-01-29 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('submissions_limit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Nouveau', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
