# Generated by Django 6.0.1 on 2026-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='CryptoTrade Pro', max_length=255)),
                ('welcome_message', models.TextField(default='Bienvenue sur CryptoTrade Pro...')),
                ('primary_color', models.CharField(default='#1a1f3a', max_length=50)),
                ('accent_color', models.CharField(default='#f7931a', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
