# Generated by Django 6.0.1 on 2026-01-30 05:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appsettings_user_formlink_user_notification_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formlink',
            name='link_id',
            field=models.CharField(default=api.models.generate_link_id, max_length=100, unique=True),
        ),
    ]
